name: 🐛 Bug Report
description: Let us know if something is expected to work, but doesn't.
title: "Bullet Chart - "
labels: bug
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Before opening a bug report please search for the behaviour in the existing issues.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: Describe the issue you are experiencing with Bullet Chart. Provide a clear and concise description of what you were trying to do and what happened, along with any error messages you encountered.
  validations:
    required: true
- type: input
  attributes: 
    label: Power BI
    description: Enter the specific Power BI version used e.g. Power BI Desktop (include the version - e.g. April 2020), Power BI service, Power BI iOS app, Power BI Android app...
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. With this options...
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Sample report
    description: Include a sample report (.PBIX zipped as .ZIP file) that reproduces the issue. If the report contains private data, please recreate the issue in a sample report with dummy data.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshot
    description: Add screenshots to help explain your problem, if applicable.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Screenshot? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false