name: 💡 Feature Request
description: Suggest an idea for this project..
title: "feature: "
labels: newFeature
body:
- type: markdown
  attributes:
    value: Thanks for submitting a feature request!
- type: textarea
  attributes:
    label: The feature request
    description: Write a clear and concise description of what the feature or problem is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed solution
    description: Share how this will benefit Bullet Chart for Power BI and its users.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Please include any other context, like screenshots or mockups, if applicable.
  validations:
    required: false